debug:
  enabled: true

operator:
  replicas: 1

kubeProxyReplacement: strict


hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: "nginx"

externalWorkloads:
  enabled: true

extraConfig:
  enable-envoy-config: "true"

# encryption:
#   enabled: true
#   type: wireguard

# etcd:
#   enabled: true
#   managed: true
#   k8sService: true

# externalIPs:
#   enabled: true

# hostPort:
#   enabled: true

# hostServices:
#   enabled: true

# nodePort:
#   enabled: true

# nodeinit:
#   enabled: true

socketLB:
  enabled: true
  hostNamespaceOnly: true

ingressController:
  enabled: true

# clustermesh:
#   useAPIServer: true
#   apiserver:
#     tls:
#       auto:
#         enabled: true
#         method: cronJob
#     service:
#       type: LoadBalancer
#   config:
#     enabled: true
#     domain: mesh.cilium.io
    # clusters:
    # - name: cluster-a
    #   address: 172.19.0.100
    #   port: 2379
    # clusters:
    # # -- Name of the cluster
    # - name: cluster1
    # # -- Address of the cluster, use this if you created DNS records for
    # # the cluster Clustermesh API server.
    #   address: cluster1.mesh.cilium.io
    # # -- Port of the cluster Clustermesh API server.
    #   port: 2379
    # # -- IPs of the cluster Clustermesh API server, use multiple ones when
    # # you have multiple IPs to access the Clustermesh API server.
    #   ips:
    #   - 172.18.255.201
    # # -- base64 encoded PEM values for the cluster client certificate, private key and certificate authority.
    #   tls:
    #     cert: ""
    #     key: ""
ipam:
  mode: kubernetes
