apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: iop-dev0
spec:
  profile: default
  components:
      ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  meshConfig:
    enableTracing: true
