# https://taskfile.dev

version: "3"

vars:
  CERTMANAGER_CHART_VER: v1.12.3

tasks:
  init:
    cmds:
      - helm repo add jetstack https://charts.jetstack.io
      - helm repo update jetstack
  check:
    cmds:
      - helm search repo jetstack/cert-manager
  install:
    deps:
      - init
    cmds:
      - |
        helm upgrade \
          --kube-context {{ .CONTEXT }} \
          --install cert-manager jetstack/cert-manager \
          --version {{ .CERTMANAGER_CHART_VER }} \
          --create-namespace \
          --namespace cert-manager-system \
          --set installCRDs=true
